"""0015_add_last_visit_profile

Revision ID: 10e8629ed805
Revises: 3b783468c1c0
Create Date: 2024-08-08 16:27:47.125794

"""
from typing import (
    Sequence,
    Union,
)

from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10e8629ed805'
down_revision: Union[str, None] = '3b783468c1c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('last_visit', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    # ### end Alembic commands ###
    op.alter_column('profiles', 'last_visit', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'last_visit')
    # ### end Alembic commands ###
