"""0013_fix_column_types

Revision ID: 6bd5d91a4387
Revises: c9ec58bd567a
Create Date: 2024-08-06 18:05:46.794079

"""
from typing import (
    Sequence,
    Union,
)

from alembic import op

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '6bd5d91a4387'
down_revision: Union[str, None] = 'c9ec58bd567a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answers', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('answers', 'right',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('category_complaints', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('complaints', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('complaints', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('complaints', 'solved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('questions', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('questions', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('questions', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('complaints', 'solved',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('complaints', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('complaints', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('category_complaints', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('answers', 'right',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('answers', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
