"""0009_add_statistic_trend

Revision ID: 91e81d4e6c0b
Revises: e45b501b244b
Create Date: 2024-07-06 11:34:31.677443

"""
from typing import (
    Sequence,
    Union,
)

from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91e81d4e6c0b'
down_revision: Union[str, None] = 'e45b501b244b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics', sa.Column('trend', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###
    op.alter_column('statistics', 'trend', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistics', 'trend')
    # ### end Alembic commands ###
