"""0010_add_month_day_statistic

Revision ID: 0cb1716cd099
Revises: 91e81d4e6c0b
Create Date: 2024-07-14 11:48:54.083760

"""
from typing import (
    Sequence,
    Union,
)

from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cb1716cd099'
down_revision: Union[str, None] = '91e81d4e6c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('place', sa.Integer(), nullable=True),
    sa.Column('rights', sa.Integer(), nullable=True),
    sa.Column('wrongs', sa.Integer(), nullable=True),
    sa.Column('trend', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_index(op.f('ix_day_statistics_id'), 'day_statistics', ['id'], unique=True)
    op.create_table('month_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('place', sa.Integer(), nullable=True),
    sa.Column('rights', sa.Integer(), nullable=True),
    sa.Column('wrongs', sa.Integer(), nullable=True),
    sa.Column('trend', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_index(op.f('ix_month_statistics_id'), 'month_statistics', ['id'], unique=True)
    op.drop_constraint('statistics_place_key', 'statistics', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('statistics_place_key', 'statistics', ['place'])
    op.drop_index(op.f('ix_month_statistics_id'), table_name='month_statistics')
    op.drop_table('month_statistics')
    op.drop_index(op.f('ix_day_statistics_id'), table_name='day_statistics')
    op.drop_table('day_statistics')
    # ### end Alembic commands ###
