"""0011_add_profile_title

Revision ID: 3cdb2c458b68
Revises: 0cb1716cd099
Create Date: 2024-07-28 16:07:25.744412

"""
from typing import (
    Sequence,
    Union,
)

from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cdb2c458b68'
down_revision: Union[str, None] = '0cb1716cd099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('best_player_title',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('best_of_the_day', sa.Integer(), nullable=False),
    sa.Column('best_of_the_month', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_index(op.f('ix_best_player_title_id'), 'best_player_title', ['id'], unique=True)
    op.drop_index('ix_test_table_id', table_name='test_table')
    op.drop_table('test_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_table_pkey')
    )
    op.create_index('ix_test_table_id', 'test_table', ['id'], unique=True)
    op.drop_index(op.f('ix_best_player_title_id'), table_name='best_player_title')
    op.drop_table('best_player_title')
    # ### end Alembic commands ###
