"""0011_add_profile_title_top

Revision ID: c280bdc3dc1e
Revises: e85d4ec674f2
Create Date: 2024-07-29 17:00:28.766200

"""
from typing import (
    Sequence,
    Union,
)

from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c280bdc3dc1e'
down_revision: Union[str, None] = '0cb1716cd099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('best_player_title',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('best_of_the_day', sa.Integer(), nullable=False),
    sa.Column('best_of_the_month', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_index(op.f('ix_best_player_title_id'), 'best_player_title', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_best_player_title_id'), table_name='best_player_title')
    op.drop_table('best_player_title')
    # ### end Alembic commands ###
