"""0012_add_perfect_rounds

Revision ID: c9ec58bd567a
Revises: c280bdc3dc1e
Create Date: 2024-07-30 13:56:36.795009

"""
from typing import (
    Sequence,
    Union,
)

from alembic import op

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'c9ec58bd567a'
down_revision: Union[str, None] = 'c280bdc3dc1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day_statistics', sa.Column('perfect_rounds', sa.Integer(), nullable=False, server_default="0"))
    op.alter_column('day_statistics', 'perfect_rounds', server_default=None)
    op.alter_column('day_statistics', 'games',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('day_statistics', 'score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('day_statistics', 'place',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('day_statistics', 'rights',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('day_statistics', 'wrongs',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('day_statistics', 'trend',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('month_statistics', sa.Column('perfect_rounds', sa.Integer(), nullable=False, server_default="0"))
    op.alter_column('month_statistics', 'perfect_rounds', server_default=None)
    op.alter_column('month_statistics', 'games',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('month_statistics', 'score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('month_statistics', 'place',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('month_statistics', 'rights',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('month_statistics', 'wrongs',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('month_statistics', 'trend',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('profiles', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('statistics', sa.Column('perfect_rounds', sa.Integer(), nullable=False, server_default="0"))
    op.alter_column('statistics', 'perfect_rounds', server_default=None)
    op.alter_column('statistics', 'games',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('statistics', 'score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('statistics', 'place',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('statistics', 'rights',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('statistics', 'wrongs',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('statistics', 'trend',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('users', 'date_joined',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'date_joined',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('statistics', 'trend',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('statistics', 'wrongs',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('statistics', 'rights',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('statistics', 'place',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('statistics', 'score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('statistics', 'games',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('statistics', 'perfect_rounds')
    op.alter_column('profiles', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('month_statistics', 'trend',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('month_statistics', 'wrongs',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('month_statistics', 'rights',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('month_statistics', 'place',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('month_statistics', 'score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('month_statistics', 'games',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('month_statistics', 'perfect_rounds')
    op.alter_column('day_statistics', 'trend',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('day_statistics', 'wrongs',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('day_statistics', 'rights',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('day_statistics', 'place',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('day_statistics', 'score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('day_statistics', 'games',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('day_statistics', 'perfect_rounds')
    # ### end Alembic commands ###
