"""0008_add_new_game_rules

Revision ID: e45b501b244b
Revises: 30948bc2bb28
Create Date: 2024-07-04 14:59:28.322276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e45b501b244b'
down_revision: Union[str, None] = '30948bc2bb28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_settings', sa.Column('right_ratio', sa.Float(), nullable=False, server_default="1.0"))
    op.add_column('game_settings', sa.Column('wrong_ratio', sa.Float(), nullable=False, server_default="-0.5"))
    # ### end Alembic commands ###
    op.alter_column('game_settings', 'right_ratio', server_default=None)
    op.alter_column('game_settings', 'wrong_ratio', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_settings', 'wrong_ratio')
    op.drop_column('game_settings', 'right_ratio')
    # ### end Alembic commands ###
