stages:
  - build
  - deploy


.docker_login: &docker_login
  - echo "$DOCKER_KEY" | docker login --username $DOCKER_USER --password-stdin $CONTAINER_REGISTRY

.clear_secrets: &clear_secrets
  - chmod +x ./.ci/scripts/clear_secrets.sh
  - ./.ci/scripts/clear_secrets.sh

.common:
  only:
    - master
  tags:
    - back


build:
  stage: build
  before_script:
    - *docker_login
  script:
    - docker build --network host -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  extends: .common

deploy:
  stage: deploy
  image: docker:20.10-git
  dependencies:
    - build
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
    - *docker_login
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker run --rm --env-file $env --network db-net $CI_REGISTRY_IMAGE -m alembic upgrade head
    - CONFIG_VERSION=$(date +%Y%m%d%H%m%s) docker stack deploy --with-registry-auth --resolve-image always -c ./.ci/docker/app.yml back
  after_script:
    - sleep 15
    - rm -r -f ~/.ssh
    - docker image prune -f -a && docker container prune -f || true
    - *clear_secrets
  extends: .common

