"""

Revision ID: 075537943389
Revises: 734928bc6a8a
Create Date: 2024-05-29 03:19:01.819101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '075537943389'
down_revision: Union[str, None] = '734928bc6a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'statistics', ['score'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statistics', type_='unique')
    # ### end Alembic commands ###
