"""0003_add_device_uuid_profile

Revision ID: 149c18f0cfe3
Revises: 075d5736b19c
Create Date: 2024-05-25 03:34:29.221689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '149c18f0cfe3'
down_revision: Union[str, None] = '075d5736b19c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('device_uuid', sa.String(length=32), nullable=False))
    op.create_index(op.f('ix_profiles_device_uuid'), 'profiles', ['device_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_device_uuid'), table_name='profiles')
    op.drop_column('profiles', 'device_uuid')
    # ### end Alembic commands ###
