"""

Revision ID: 1ffc223c1a3b
Revises: e1bcb874766f
Create Date: 2024-05-28 22:54:11.785842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ffc223c1a3b'
down_revision: Union[str, None] = 'e1bcb874766f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('statictics_place_key', 'statictics', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('statictics_place_key', 'statictics', ['place'])
    # ### end Alembic commands ###
