"""

Revision ID: 20ca50a2c076
Revises: 50aa2213b3b4
Create Date: 2024-05-29 18:59:36.412414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20ca50a2c076'
down_revision: Union[str, None] = '50aa2213b3b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('statistics_score_key', 'statistics', type_='unique')
    op.create_unique_constraint(None, 'statistics', ['place'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statistics', type_='unique')
    op.create_unique_constraint('statistics_score_key', 'statistics', ['score'])
    # ### end Alembic commands ###
