"""

Revision ID: 50aa2213b3b4
Revises: 7806798ebb1a
Create Date: 2024-05-29 18:59:19.343445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50aa2213b3b4'
down_revision: Union[str, None] = '7806798ebb1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'statistics', ['score'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statistics', type_='unique')
    # ### end Alembic commands ###
