"""0005_add_statistic

Revision ID: 699eab6e0fef
Revises: 64182c1808f8
Create Date: 2024-05-25 11:52:34.060599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '699eab6e0fef'
down_revision: Union[str, None] = '64182c1808f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statictics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('place', sa.Integer(), nullable=True),
    sa.Column('rights', sa.Integer(), nullable=True),
    sa.Column('wrongs', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_index(op.f('ix_statictics_id'), 'statictics', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statictics_id'), table_name='statictics')
    op.drop_table('statictics')
    # ### end Alembic commands ###
