"""

Revision ID: 734928bc6a8a
Revises: 91781d31ff57
Create Date: 2024-05-29 02:54:55.553612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '734928bc6a8a'
down_revision: Union[str, None] = '91781d31ff57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('place', sa.Integer(), nullable=True),
    sa.Column('rights', sa.Integer(), nullable=True),
    sa.Column('wrongs', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_index(op.f('ix_statistics_id'), 'statistics', ['id'], unique=True)
    op.drop_index('ix_statictics_id', table_name='statictics')
    op.drop_table('statictics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statictics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('games', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('place', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rights', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wrongs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name='statictics_profile_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='statictics_pkey'),
    sa.UniqueConstraint('profile_id', name='statictics_profile_id_key')
    )
    op.create_index('ix_statictics_id', 'statictics', ['id'], unique=True)
    op.drop_index(op.f('ix_statistics_id'), table_name='statistics')
    op.drop_table('statistics')
    # ### end Alembic commands ###
