"""

Revision ID: 7806798ebb1a
Revises: 075537943389
Create Date: 2024-05-29 18:50:55.396435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7806798ebb1a'
down_revision: Union[str, None] = '075537943389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('statistics_score_key', 'statistics', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('statistics_score_key', 'statistics', ['score'])
    # ### end Alembic commands ###
