"""

Revision ID: 91781d31ff57
Revises: e94474f4a6bd
Create Date: 2024-05-28 23:08:45.063564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91781d31ff57'
down_revision: Union[str, None] = 'e94474f4a6bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('statictics_place_key', 'statictics', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('statictics_place_key', 'statictics', ['place'])
    # ### end Alembic commands ###
