"""

Revision ID: e134752b8b56
Revises: da1231b6c2d7
Create Date: 2024-05-25 17:46:21.390978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e134752b8b56'
down_revision: Union[str, None] = 'da1231b6c2d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('statictics_place_key', 'statictics', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('statictics_place_key', 'statictics', ['place'])
    # ### end Alembic commands ###
