"""

Revision ID: e1bcb874766f
Revises: e134752b8b56
Create Date: 2024-05-28 22:41:00.205694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1bcb874766f'
down_revision: Union[str, None] = 'e134752b8b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'statictics', ['place'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statictics', type_='unique')
    # ### end Alembic commands ###
