"""0004_create_game_settings

Revision ID: e6a82a62ea8b
Revises: 0914bac9c5f1
Create Date: 2024-06-11 16:58:45.668467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker

from apps.game_settings.models import GameSettings

# revision identifiers, used by Alembic.
revision: str = 'e6a82a62ea8b'
down_revision: Union[str, None] = '0914bac9c5f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_round', sa.Integer(), nullable=False),
    sa.Column('question_limit', sa.Integer(), nullable=False),
    sa.Column('max_energy', sa.Integer(), nullable=False),
    sa.Column('start_energy', sa.Integer(), nullable=False),
    sa.Column('energy_for_ad', sa.Integer(), nullable=False),
    sa.Column('round_cost', sa.Integer(), nullable=False),
    sa.Column('question_skip_cost', sa.Integer(), nullable=False),
    sa.Column('energy_perfect_round', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_settings_id'), 'game_settings', ['id'], unique=True)
    # ### end Alembic commands ###

    bind = op.get_bind()
    Session = sessionmaker(bind=bind)
    session = Session()
    new_game_settings = GameSettings(
        time_round=20,
        question_limit=10,
        max_energy=100,
        start_energy=100,
        energy_for_ad=100,
        round_cost=10,
        question_skip_cost=5,
        energy_perfect_round=5
    )
    session.add(new_game_settings)
    session.commit()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_settings_id'), table_name='game_settings')
    op.drop_table('game_settings')
    # ### end Alembic commands ###
