version: "3.8"

services:
  fastapi-quiz:
    container_name: fastapi-quiz
    build:
      context: ../../
      dockerfile: Dockerfile
    env_file:
      - ../../.env
    tty: true
    ports:
      - "8000:8000"
    networks:
      - dev-net
    volumes:
      - ../../src/core:/app/core
      - ../../q.json:/app/q.json
#      - ../../database.log:/app/database.log

  celery-beat:
    container_name: celery-beat
    build:
      context: ../../
      dockerfile: Dockerfile
    command: [ "-m", "celery", "-A", "services.tasks.celery_app", "beat", "-l", "info" ]
    env_file:
      - ../../.env
    tty: true
    networks:
      - dev-net

  celery-worker:
    container_name: celery-worker
    build:
      context: ../../
      dockerfile: Dockerfile
    command: [ "-m", "celery", "-A", "services.tasks.celery_app", "worker", "-l", "info" ]
    env_file:
      - ../../.env
    tty: true
    networks:
      - dev-net

networks:
  dev-net:
    name: dev-net
    driver: bridge
