version: "3.8"

services:
  fastapi-quiz:
    container_name: fastapi-quiz
    build:
      context: ../../
      dockerfile: Dockerfile
    env_file:
      - ../../.env
    tty: true
    ports:
      - "8000:8000"
    networks:
      - dev-net
    volumes:
      - ../../core:/app/core


networks:
  dev-net:
    name: dev-net
    driver: bridge
