services:
  main-app:
    image: ${CI_REGISTRY_IMAGE}
    env_file:
      - $env
    tty: true
    ports:
      - "8000:8000"
    networks:
       - nginx-net
       - db-net
       - service-net
    secrets:
      - remote_config
    healthcheck:
      test: "curl --fail http://localhost:8000/api/v1/healthcheck/"
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 60s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.TAG==prod-1"
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 30s
        monitor: 120s
      rollback_config:
        parallelism: 0
        order: stop-first

  celery-worker:
    image: ${CI_REGISTRY_IMAGE}
    command: [ "-m", "celery", "-A", "core.services.tasks.celery_app", "worker", "-l", "info" ]
    env_file:
      - $env
    tty: true
    networks:
       - db-net
       - service-net
    secrets:
      - remote_config
    healthcheck:
      test: [ "CMD-SHELL", "[[ $$(($$(date +%s)-$$(stat -c %Y /tmp/celery_heartbeat))) -gt 2 ]] && exit 1 || exit 0" ]
      interval: 10s
      timeout: 2s
      retries: 2
      start_period: 30s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.TAG==prod-1"
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 30s
        monitor: 120s
      rollback_config:
        parallelism: 0
        order: stop-first

  celery-beat:
    image: ${CI_REGISTRY_IMAGE}
    command: [ "-m", "celery", "-A", "core.services.tasks.celery_app", "beat", "-l", "info" ]
    env_file:
      - $env
    tty: true
    networks:
      - db-net
      - service-net
    secrets:
      - remote_config
    healthcheck:
      test: [ "CMD-SHELL", "[[ $$(($$(date +%s)-$$(stat -c %Y /tmp/celery_heartbeat))) -gt 61 ]] && exit 1 || exit 0" ]
      interval: 30s
      timeout: 2s
      retries: 2
      start_period: 1m
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.TAG==prod-1"
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 30s
        monitor: 120s
      rollback_config:
        parallelism: 0
        order: stop-first

networks:
  nginx-net:
    external: true
  db-net:
    external: true
  service-net:
    external: true


secrets:
  remote_config:
    name: remote_config-${CONFIG_VERSION:-0}
    file: $FIREBASE_JSON_CONF